### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dlorent** [sla89/hassio-kostal-piko#2]
Hi.

Could you perhaps describe what kostal piko model/version you have tested with
and if login is required (or if it's using the default) - or if the api isnt protected at all ?

I followed the instructions, but looks like it's unable to fetch the data.

PIKO 5.5

**Comment by BastianPlatt** [comment]
Hi, 

I am having the same issue with Piko 5.5. - would appreciate any help guidance. 

I can find all the devices but they are not accessable - I don not get data as it says: 
"sensor.kostal_piko_autarky_day" - Entity does not have a unique ID 

Thanks a lot and best

**Comment by sla89** [comment]
Sorry for the late response. For some strange reason I do not get any notifications...

For some people in the community it worked, see [HA forum](https://community.home-assistant.io/t/kostal-piko-and-kostal-piko-iq-support/381263) but the somebody else in that thread told me that it does not work for him.

I will implement some authentication because up until now it worked without any authentication...

@BastianPlatt you error looks like a different issue to me... maybe you can create another ticket please?

I have implemented this plugin for some people in the community (Home Assistant and a German user forum). I own a PIKO IQ which has a complete different approach to query the data. So I cannot test anything when I make changes and I have to rely on the people who asked me to implement it for them.

I have created a pull request (see #3 to see what I have changed). Maybe you can give it a try with the code from that branch and let me know if it works for you: [go to branch](https://github.com/sla89/hassio-kostal-piko/tree/add_authentication)
Simply replace the files.

I have also updated the read me - is it now better?

@dlorent can you please check the logs at Settings -> Setzings - > Logs?
Someboy reported a decoding issue which leads to exactly your described behavior.

@BastianPlatt how have you installed the integration?

**Comment by dlorent** [comment]
@sla89 - Thank you for getting back to us.
I will have some time to check within the next few days, and i will get back with the results.

Thanks

**Comment by dlorent** [comment]
@sla89 
The problem is probably related to an old kostal piko 5.5 installation of mine, which is from 2012 with a firmware of 3.78.
i suspect it's an older firmware which does not support /api access.

So i gues you should just add to the readme which versions it's tested with (and which are known not to work..)

**Comment by sla89** [comment]
I know from the community that it works for Piko 5.5 and 17.

I started asking the people to tell me which firmware versions they use. So far I know that two people are having a Piko 12, 15 and 17 with the following component version

UI 06.53
FW 06.17
HW 0100
PAR 03.50

and the integration works as-is.

It doesn't work for PIKO 4.2 with firmware version 3.74.

What happens when you call the following url in your browser (replace IP with the IP of your inverter)

http://IP/api/dxs.json?dxsEntries=33556736

Maye you are right and your firmware simply does not expose the data :(

**Comment by sla89** [comment]
When you press F12 in your browser (edge, chrome or firefox) a new window will open.
Can you there select the network tab and visit the webinterface of your inverter, please?
Do you see something like this:
![image](https://user-images.githubusercontent.com/4637490/177640454-58577a7a-ed39-4ca5-8f29-85906537fed4.png)

If not, your inverter does not expose the data via DXS entries and my integration does not work.
You can then try out this integration: https://github.com/rcasula/kostalpiko-homeassistant

I have also updated the README.

**Comment by dlorent** [comment]
@sla89 Unfortuantly not - it's *.fhtml page thats being rendered, no dxs.json at all.

Thank you for the help tho! :)

**Comment by sla89** [comment]
You are welcome. I close the issue.
